server:
  port: 8082
spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/epidemicFreight
#    username: root
#    password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/trainTicketer
    username: root
    password: 123456
  task:
    execution:
      pool:
        max-size: 10
        core-size: 3
        keep-alive: 230s
        queue-capacity: 1000
      thread-name-prefix: thread
  #  main:
  #    allow-bean-definition-overriding: true
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false #将视图警告信息抹去
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  redis:
    port: 6379
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 80
        max-wait: 30000
        timeout: 3000
